#ifndef CONFIG_H
#define CONFIG_H

// Repeat unit configuration
#define REPEAT_SIZE 178

// Default simulation parameters
#define DEFAULT_INITIAL_SIZE 10000
#define DEFAULT_MIN_ARRAY_SIZE 300
#define DEFAULT_MAX_ARRAY_SIZE 50000

#define DEFAULT_INDEL_RATE 0.5f
#define DEFAULT_INDEL_SIZE_LAMBDA 7.6f
#define DEFAULT_SNP_RATE 0.1f

// Visualization
#define GRID_WIDTH 100
#define TILE_SIZE 8
#define WINDOW_WIDTH 1600
#define WINDOW_HEIGHT 1000

// UI layout
#define PANEL_X 1150
#define PANEL_WIDTH 420

// CEN178 consensus monomer
static const char DEFAULT_MONOMER[REPEAT_SIZE + 1] =
    "AGTATAAGAACTTAAACCGCAACCCGATCTTAAAAGCCTAAGTAGTGTTTCCTTGTTAGAA"
    "GACACAAAGCCAAAGACTCATATGGACTTTGGCTACACCATGAAAGCTTTGAGAAGCAAGA"
    "AGAAGGTTGGTTAGTGTTTTGGAGTCGAATATGACTTGATGTCATGTGTATGATTG";

// DNA bases
static const char BASES[4] = {'A', 'C', 'G', 'T'};

#endif // CONFIG_H
